// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/v1/marketdata.proto

package marketdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Side represents the side of a market event.
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_marketdata_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_api_proto_v1_marketdata_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_marketdata_proto_rawDescGZIP(), []int{0}
}

// MarketEvent is the top-level envelope for all streaming messages over WebSocket.
// It wraps specific event payloads.
type MarketEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ticker symbol this event belongs to (e.g., "AAPL")
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Event generation timestamp in Unix milliseconds
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Global sequence number for the stream (useful for gap detection without decoding the payload)
	SequenceNumber uint64 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// The specific event payload
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*MarketEvent_Tick
	//	*MarketEvent_OrderBookUpdate
	//	*MarketEvent_Heartbeat
	//	*MarketEvent_Snapshot
	//	*MarketEvent_ReplayResponse
	Payload       isMarketEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketEvent) Reset() {
	*x = MarketEvent{}
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketEvent) ProtoMessage() {}

func (x *MarketEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketEvent.ProtoReflect.Descriptor instead.
func (*MarketEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_marketdata_proto_rawDescGZIP(), []int{0}
}

func (x *MarketEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MarketEvent) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MarketEvent) GetPayload() isMarketEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MarketEvent) GetTick() *Tick {
	if x != nil {
		if x, ok := x.Payload.(*MarketEvent_Tick); ok {
			return x.Tick
		}
	}
	return nil
}

func (x *MarketEvent) GetOrderBookUpdate() *OrderBookUpdate {
	if x != nil {
		if x, ok := x.Payload.(*MarketEvent_OrderBookUpdate); ok {
			return x.OrderBookUpdate
		}
	}
	return nil
}

func (x *MarketEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*MarketEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *MarketEvent) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Payload.(*MarketEvent_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *MarketEvent) GetReplayResponse() *ReplayResponse {
	if x != nil {
		if x, ok := x.Payload.(*MarketEvent_ReplayResponse); ok {
			return x.ReplayResponse
		}
	}
	return nil
}

type isMarketEvent_Payload interface {
	isMarketEvent_Payload()
}

type MarketEvent_Tick struct {
	Tick *Tick `protobuf:"bytes,4,opt,name=tick,proto3,oneof"`
}

type MarketEvent_OrderBookUpdate struct {
	OrderBookUpdate *OrderBookUpdate `protobuf:"bytes,5,opt,name=order_book_update,json=orderBookUpdate,proto3,oneof"`
}

type MarketEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,6,opt,name=heartbeat,proto3,oneof"`
}

type MarketEvent_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,7,opt,name=snapshot,proto3,oneof"`
}

type MarketEvent_ReplayResponse struct {
	ReplayResponse *ReplayResponse `protobuf:"bytes,8,opt,name=replay_response,json=replayResponse,proto3,oneof"`
}

func (*MarketEvent_Tick) isMarketEvent_Payload() {}

func (*MarketEvent_OrderBookUpdate) isMarketEvent_Payload() {}

func (*MarketEvent_Heartbeat) isMarketEvent_Payload() {}

func (*MarketEvent_Snapshot) isMarketEvent_Payload() {}

func (*MarketEvent_ReplayResponse) isMarketEvent_Payload() {}

// Tick represents a single trade execution or quote update.
type Tick struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Price  float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Volume float64                `protobuf:"fixed64,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Side   Side                   `protobuf:"varint,3,opt,name=side,proto3,enum=rtmds.marketdata.v1.Side" json:"side,omitempty"`
	// Optional exchange identifier where the tick occurred
	Exchange string `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Optional unique trade/tick identifier
	TradeId       string `protobuf:"bytes,5,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tick) Reset() {
	*x = Tick{}
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_marketdata_proto_rawDescGZIP(), []int{1}
}

func (x *Tick) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tick) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Tick) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Tick) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Tick) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

// Level represents a single price level in an order book.
// We keep this as a message rather than flat struct to allow extensibility (e.g., adding order_count)
type Level struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Volume        float64                `protobuf:"fixed64,2,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level) Reset() {
	*x = Level{}
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_marketdata_proto_rawDescGZIP(), []int{2}
}

func (x *Level) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Level) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

// OrderBookUpdate represents a change to the L2/L3 order book.
type OrderBookUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Bids  []*Level               `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks  []*Level               `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	// If true, this message represents the full book state rather than a delta update
	IsSnapshot    bool `protobuf:"varint,3,opt,name=is_snapshot,json=isSnapshot,proto3" json:"is_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookUpdate) Reset() {
	*x = OrderBookUpdate{}
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookUpdate) ProtoMessage() {}

func (x *OrderBookUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookUpdate.ProtoReflect.Descriptor instead.
func (*OrderBookUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_marketdata_proto_rawDescGZIP(), []int{3}
}

func (x *OrderBookUpdate) GetBids() []*Level {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderBookUpdate) GetAsks() []*Level {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *OrderBookUpdate) GetIsSnapshot() bool {
	if x != nil {
		return x.IsSnapshot
	}
	return false
}

// Heartbeat represents a connection keep-alive or sequence marker.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_marketdata_proto_rawDescGZIP(), []int{4}
}

// Snapshot represents a summary of current market conditions.
type Snapshot struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	LastPrice  float64                `protobuf:"fixed64,1,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	LastVolume float64                `protobuf:"fixed64,2,opt,name=last_volume,json=lastVolume,proto3" json:"last_volume,omitempty"`
	High       float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low        float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Open       float64                `protobuf:"fixed64,5,opt,name=open,proto3" json:"open,omitempty"`
	Close      float64                `protobuf:"fixed64,6,opt,name=close,proto3" json:"close,omitempty"`
	// Optional full order book snapshot attached to the summary
	OrderBook     *OrderBookUpdate `protobuf:"bytes,7,opt,name=order_book,json=orderBook,proto3" json:"order_book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_marketdata_proto_rawDescGZIP(), []int{5}
}

func (x *Snapshot) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *Snapshot) GetLastVolume() float64 {
	if x != nil {
		return x.LastVolume
	}
	return 0
}

func (x *Snapshot) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Snapshot) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Snapshot) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Snapshot) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Snapshot) GetOrderBook() *OrderBookUpdate {
	if x != nil {
		return x.OrderBook
	}
	return nil
}

// ReplayResponse indicates the status of a historical data replay request.
type ReplayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if this is the final message of the replay session
	IsComplete bool `protobuf:"varint,1,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	// The starting sequence number of the replay chunk
	StartSequence uint64 `protobuf:"varint,2,opt,name=start_sequence,json=startSequence,proto3" json:"start_sequence,omitempty"`
	// The ending sequence number of the replay chunk
	EndSequence   uint64 `protobuf:"varint,3,opt,name=end_sequence,json=endSequence,proto3" json:"end_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayResponse) Reset() {
	*x = ReplayResponse{}
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayResponse) ProtoMessage() {}

func (x *ReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_marketdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayResponse.ProtoReflect.Descriptor instead.
func (*ReplayResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_marketdata_proto_rawDescGZIP(), []int{6}
}

func (x *ReplayResponse) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *ReplayResponse) GetStartSequence() uint64 {
	if x != nil {
		return x.StartSequence
	}
	return 0
}

func (x *ReplayResponse) GetEndSequence() uint64 {
	if x != nil {
		return x.EndSequence
	}
	return 0
}

var File_api_proto_v1_marketdata_proto protoreflect.FileDescriptor

const file_api_proto_v1_marketdata_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/v1/marketdata.proto\x12\x13rtmds.marketdata.v1\"\xcf\x03\n" +
	"\vMarketEvent\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x04R\x0esequenceNumber\x12/\n" +
	"\x04tick\x18\x04 \x01(\v2\x19.rtmds.marketdata.v1.TickH\x00R\x04tick\x12R\n" +
	"\x11order_book_update\x18\x05 \x01(\v2$.rtmds.marketdata.v1.OrderBookUpdateH\x00R\x0forderBookUpdate\x12>\n" +
	"\theartbeat\x18\x06 \x01(\v2\x1e.rtmds.marketdata.v1.HeartbeatH\x00R\theartbeat\x12;\n" +
	"\bsnapshot\x18\a \x01(\v2\x1d.rtmds.marketdata.v1.SnapshotH\x00R\bsnapshot\x12N\n" +
	"\x0freplay_response\x18\b \x01(\v2#.rtmds.marketdata.v1.ReplayResponseH\x00R\x0ereplayResponseB\t\n" +
	"\apayloadJ\x04\b\t\x10\x10\"\xa0\x01\n" +
	"\x04Tick\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\x01R\x06volume\x12-\n" +
	"\x04side\x18\x03 \x01(\x0e2\x19.rtmds.marketdata.v1.SideR\x04side\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12\x19\n" +
	"\btrade_id\x18\x05 \x01(\tR\atradeIdJ\x04\b\x06\x10\v\"5\n" +
	"\x05Level\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\x01R\x06volume\"\x98\x01\n" +
	"\x0fOrderBookUpdate\x12.\n" +
	"\x04bids\x18\x01 \x03(\v2\x1a.rtmds.marketdata.v1.LevelR\x04bids\x12.\n" +
	"\x04asks\x18\x02 \x03(\v2\x1a.rtmds.marketdata.v1.LevelR\x04asks\x12\x1f\n" +
	"\vis_snapshot\x18\x03 \x01(\bR\n" +
	"isSnapshotJ\x04\b\x04\x10\v\"\v\n" +
	"\tHeartbeat\"\xe5\x01\n" +
	"\bSnapshot\x12\x1d\n" +
	"\n" +
	"last_price\x18\x01 \x01(\x01R\tlastPrice\x12\x1f\n" +
	"\vlast_volume\x18\x02 \x01(\x01R\n" +
	"lastVolume\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x12\n" +
	"\x04open\x18\x05 \x01(\x01R\x04open\x12\x14\n" +
	"\x05close\x18\x06 \x01(\x01R\x05close\x12C\n" +
	"\n" +
	"order_book\x18\a \x01(\v2$.rtmds.marketdata.v1.OrderBookUpdateR\torderBookJ\x04\b\b\x10\x10\"\x81\x01\n" +
	"\x0eReplayResponse\x12\x1f\n" +
	"\vis_complete\x18\x01 \x01(\bR\n" +
	"isComplete\x12%\n" +
	"\x0estart_sequence\x18\x02 \x01(\x04R\rstartSequence\x12!\n" +
	"\fend_sequence\x18\x03 \x01(\x04R\vendSequenceJ\x04\b\x04\x10\v*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02B0Z.github.com/sumit/rtmds/api/proto/v1;marketdatab\x06proto3"

var (
	file_api_proto_v1_marketdata_proto_rawDescOnce sync.Once
	file_api_proto_v1_marketdata_proto_rawDescData []byte
)

func file_api_proto_v1_marketdata_proto_rawDescGZIP() []byte {
	file_api_proto_v1_marketdata_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_marketdata_proto_rawDesc), len(file_api_proto_v1_marketdata_proto_rawDesc)))
	})
	return file_api_proto_v1_marketdata_proto_rawDescData
}

var file_api_proto_v1_marketdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_v1_marketdata_proto_goTypes = []any{
	(Side)(0),               // 0: rtmds.marketdata.v1.Side
	(*MarketEvent)(nil),     // 1: rtmds.marketdata.v1.MarketEvent
	(*Tick)(nil),            // 2: rtmds.marketdata.v1.Tick
	(*Level)(nil),           // 3: rtmds.marketdata.v1.Level
	(*OrderBookUpdate)(nil), // 4: rtmds.marketdata.v1.OrderBookUpdate
	(*Heartbeat)(nil),       // 5: rtmds.marketdata.v1.Heartbeat
	(*Snapshot)(nil),        // 6: rtmds.marketdata.v1.Snapshot
	(*ReplayResponse)(nil),  // 7: rtmds.marketdata.v1.ReplayResponse
}
var file_api_proto_v1_marketdata_proto_depIdxs = []int32{
	2, // 0: rtmds.marketdata.v1.MarketEvent.tick:type_name -> rtmds.marketdata.v1.Tick
	4, // 1: rtmds.marketdata.v1.MarketEvent.order_book_update:type_name -> rtmds.marketdata.v1.OrderBookUpdate
	5, // 2: rtmds.marketdata.v1.MarketEvent.heartbeat:type_name -> rtmds.marketdata.v1.Heartbeat
	6, // 3: rtmds.marketdata.v1.MarketEvent.snapshot:type_name -> rtmds.marketdata.v1.Snapshot
	7, // 4: rtmds.marketdata.v1.MarketEvent.replay_response:type_name -> rtmds.marketdata.v1.ReplayResponse
	0, // 5: rtmds.marketdata.v1.Tick.side:type_name -> rtmds.marketdata.v1.Side
	3, // 6: rtmds.marketdata.v1.OrderBookUpdate.bids:type_name -> rtmds.marketdata.v1.Level
	3, // 7: rtmds.marketdata.v1.OrderBookUpdate.asks:type_name -> rtmds.marketdata.v1.Level
	4, // 8: rtmds.marketdata.v1.Snapshot.order_book:type_name -> rtmds.marketdata.v1.OrderBookUpdate
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_v1_marketdata_proto_init() }
func file_api_proto_v1_marketdata_proto_init() {
	if File_api_proto_v1_marketdata_proto != nil {
		return
	}
	file_api_proto_v1_marketdata_proto_msgTypes[0].OneofWrappers = []any{
		(*MarketEvent_Tick)(nil),
		(*MarketEvent_OrderBookUpdate)(nil),
		(*MarketEvent_Heartbeat)(nil),
		(*MarketEvent_Snapshot)(nil),
		(*MarketEvent_ReplayResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_marketdata_proto_rawDesc), len(file_api_proto_v1_marketdata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_marketdata_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_marketdata_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_marketdata_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_marketdata_proto_msgTypes,
	}.Build()
	File_api_proto_v1_marketdata_proto = out.File
	file_api_proto_v1_marketdata_proto_goTypes = nil
	file_api_proto_v1_marketdata_proto_depIdxs = nil
}
