apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rtmds-ingress
  namespace: rtmds
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "rtmds-server"
spec:
  rules:
    - host: api.rtmds.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rtmds-server
                port:
                  number: 8080
    - host: grafana.rtmds.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
