// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import "strconv"

type EventPayload byte

const (
	EventPayloadNONE            EventPayload = 0
	EventPayloadTick            EventPayload = 1
	EventPayloadOrderBookUpdate EventPayload = 2
	EventPayloadHeartbeat       EventPayload = 3
	EventPayloadSnapshot        EventPayload = 4
	EventPayloadReplayResponse  EventPayload = 5
)

var EnumNamesEventPayload = map[EventPayload]string{
	EventPayloadNONE:            "NONE",
	EventPayloadTick:            "Tick",
	EventPayloadOrderBookUpdate: "OrderBookUpdate",
	EventPayloadHeartbeat:       "Heartbeat",
	EventPayloadSnapshot:        "Snapshot",
	EventPayloadReplayResponse:  "ReplayResponse",
}

var EnumValuesEventPayload = map[string]EventPayload{
	"NONE":            EventPayloadNONE,
	"Tick":            EventPayloadTick,
	"OrderBookUpdate": EventPayloadOrderBookUpdate,
	"Heartbeat":       EventPayloadHeartbeat,
	"Snapshot":        EventPayloadSnapshot,
	"ReplayResponse":  EventPayloadReplayResponse,
}

func (v EventPayload) String() string {
	if s, ok := EnumNamesEventPayload[v]; ok {
		return s
	}
	return "EventPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
