// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Level struct {
	_tab flatbuffers.Struct
}

func (rcv *Level) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Level) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Level) Price() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Level) MutatePrice(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Level) Volume() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *Level) MutateVolume(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateLevel(builder *flatbuffers.Builder, price float64, volume float64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependFloat64(volume)
	builder.PrependFloat64(price)
	return builder.Offset()
}
