// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MarketEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsMarketEvent(buf []byte, offset flatbuffers.UOffsetT) *MarketEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MarketEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishMarketEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMarketEvent(buf []byte, offset flatbuffers.UOffsetT) *MarketEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MarketEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMarketEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MarketEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MarketEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MarketEvent) Symbol() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MarketEvent) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MarketEvent) MutateTimestamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *MarketEvent) SequenceNumber() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MarketEvent) MutateSequenceNumber(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *MarketEvent) PayloadType() EventPayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return EventPayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MarketEvent) MutatePayloadType(n EventPayload) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func (rcv *MarketEvent) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func MarketEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MarketEventAddSymbol(builder *flatbuffers.Builder, symbol flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(symbol), 0)
}
func MarketEventAddTimestamp(builder *flatbuffers.Builder, timestamp int64) {
	builder.PrependInt64Slot(1, timestamp, 0)
}
func MarketEventAddSequenceNumber(builder *flatbuffers.Builder, sequenceNumber uint64) {
	builder.PrependUint64Slot(2, sequenceNumber, 0)
}
func MarketEventAddPayloadType(builder *flatbuffers.Builder, payloadType EventPayload) {
	builder.PrependByteSlot(3, byte(payloadType), 0)
}
func MarketEventAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(payload), 0)
}
func MarketEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
