// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OrderBookUpdate struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderBookUpdate(buf []byte, offset flatbuffers.UOffsetT) *OrderBookUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderBookUpdate{}
	x.Init(buf, n+offset)
	return x
}

func FinishOrderBookUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOrderBookUpdate(buf []byte, offset flatbuffers.UOffsetT) *OrderBookUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OrderBookUpdate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOrderBookUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OrderBookUpdate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderBookUpdate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderBookUpdate) Bids(obj *Level, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 16
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *OrderBookUpdate) BidsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *OrderBookUpdate) Asks(obj *Level, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 16
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *OrderBookUpdate) AsksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *OrderBookUpdate) IsSnapshot() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OrderBookUpdate) MutateIsSnapshot(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func OrderBookUpdateStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func OrderBookUpdateAddBids(builder *flatbuffers.Builder, bids flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bids), 0)
}
func OrderBookUpdateStartBidsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(16, numElems, 8)
}
func OrderBookUpdateAddAsks(builder *flatbuffers.Builder, asks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(asks), 0)
}
func OrderBookUpdateStartAsksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(16, numElems, 8)
}
func OrderBookUpdateAddIsSnapshot(builder *flatbuffers.Builder, isSnapshot bool) {
	builder.PrependBoolSlot(2, isSnapshot, false)
}
func OrderBookUpdateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
