// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReplayResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsReplayResponse(buf []byte, offset flatbuffers.UOffsetT) *ReplayResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReplayResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishReplayResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsReplayResponse(buf []byte, offset flatbuffers.UOffsetT) *ReplayResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReplayResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedReplayResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ReplayResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReplayResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReplayResponse) IsComplete() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ReplayResponse) MutateIsComplete(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *ReplayResponse) StartSequence() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ReplayResponse) MutateStartSequence(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *ReplayResponse) EndSequence() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ReplayResponse) MutateEndSequence(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func ReplayResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ReplayResponseAddIsComplete(builder *flatbuffers.Builder, isComplete bool) {
	builder.PrependBoolSlot(0, isComplete, false)
}
func ReplayResponseAddStartSequence(builder *flatbuffers.Builder, startSequence uint64) {
	builder.PrependUint64Slot(1, startSequence, 0)
}
func ReplayResponseAddEndSequence(builder *flatbuffers.Builder, endSequence uint64) {
	builder.PrependUint64Slot(2, endSequence, 0)
}
func ReplayResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
