// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import "strconv"

type Side int8

const (
	SideUnspecified Side = 0
	SideBuy         Side = 1
	SideSell        Side = 2
)

var EnumNamesSide = map[Side]string{
	SideUnspecified: "Unspecified",
	SideBuy:         "Buy",
	SideSell:        "Sell",
}

var EnumValuesSide = map[string]Side{
	"Unspecified": SideUnspecified,
	"Buy":         SideBuy,
	"Sell":        SideSell,
}

func (v Side) String() string {
	if s, ok := EnumNamesSide[v]; ok {
		return s
	}
	return "Side(" + strconv.FormatInt(int64(v), 10) + ")"
}
