// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Snapshot struct {
	_tab flatbuffers.Table
}

func GetRootAsSnapshot(buf []byte, offset flatbuffers.UOffsetT) *Snapshot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Snapshot{}
	x.Init(buf, n+offset)
	return x
}

func FinishSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSnapshot(buf []byte, offset flatbuffers.UOffsetT) *Snapshot {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Snapshot{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Snapshot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Snapshot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Snapshot) LastPrice() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Snapshot) MutateLastPrice(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *Snapshot) LastVolume() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Snapshot) MutateLastVolume(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func (rcv *Snapshot) High() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Snapshot) MutateHigh(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func (rcv *Snapshot) Low() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Snapshot) MutateLow(n float64) bool {
	return rcv._tab.MutateFloat64Slot(10, n)
}

func (rcv *Snapshot) Open() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Snapshot) MutateOpen(n float64) bool {
	return rcv._tab.MutateFloat64Slot(12, n)
}

func (rcv *Snapshot) Close() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Snapshot) MutateClose(n float64) bool {
	return rcv._tab.MutateFloat64Slot(14, n)
}

func (rcv *Snapshot) OrderBook(obj *OrderBookUpdate) *OrderBookUpdate {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OrderBookUpdate)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SnapshotStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func SnapshotAddLastPrice(builder *flatbuffers.Builder, lastPrice float64) {
	builder.PrependFloat64Slot(0, lastPrice, 0.0)
}
func SnapshotAddLastVolume(builder *flatbuffers.Builder, lastVolume float64) {
	builder.PrependFloat64Slot(1, lastVolume, 0.0)
}
func SnapshotAddHigh(builder *flatbuffers.Builder, high float64) {
	builder.PrependFloat64Slot(2, high, 0.0)
}
func SnapshotAddLow(builder *flatbuffers.Builder, low float64) {
	builder.PrependFloat64Slot(3, low, 0.0)
}
func SnapshotAddOpen(builder *flatbuffers.Builder, open float64) {
	builder.PrependFloat64Slot(4, open, 0.0)
}
func SnapshotAddClose(builder *flatbuffers.Builder, close float64) {
	builder.PrependFloat64Slot(5, close, 0.0)
}
func SnapshotAddOrderBook(builder *flatbuffers.Builder, orderBook flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(orderBook), 0)
}
func SnapshotEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
