// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Tick struct {
	_tab flatbuffers.Table
}

func GetRootAsTick(buf []byte, offset flatbuffers.UOffsetT) *Tick {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Tick{}
	x.Init(buf, n+offset)
	return x
}

func FinishTickBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTick(buf []byte, offset flatbuffers.UOffsetT) *Tick {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Tick{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTickBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Tick) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Tick) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Tick) Price() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Tick) MutatePrice(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *Tick) Volume() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Tick) MutateVolume(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func (rcv *Tick) Side() Side {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return Side(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Tick) MutateSide(n Side) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *Tick) Exchange() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Tick) TradeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TickStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func TickAddPrice(builder *flatbuffers.Builder, price float64) {
	builder.PrependFloat64Slot(0, price, 0.0)
}
func TickAddVolume(builder *flatbuffers.Builder, volume float64) {
	builder.PrependFloat64Slot(1, volume, 0.0)
}
func TickAddSide(builder *flatbuffers.Builder, side Side) {
	builder.PrependInt8Slot(2, int8(side), 0)
}
func TickAddExchange(builder *flatbuffers.Builder, exchange flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(exchange), 0)
}
func TickAddTradeId(builder *flatbuffers.Builder, tradeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(tradeId), 0)
}
func TickEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
