apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
  - gateway.yaml
  - publisher.yaml
  - feed-generator.yaml
  - topic-manager.yaml
  - replay-api.yaml
  - snapshot-service.yaml
  - recovery-manager.yaml
